#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --no-vsync &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
xbindkeys &
feh --bg-scale /usr/share/pixmaps/wallpaper.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true

